[package]
name = "rocksdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.22.0"
rand = { workspace = true }
common = { path = "../common" }
