[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["ws", "json"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.5.0", features = ["cors"] }
lazy_static = "1"
