[package]
name = "mach-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
mach-server = { path = "../mach-server" }
workload = { path = "../workload" }
