[package]
name = "matrix-multiply"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_affinity = "0.8.1"
thread-priority = "0.16.0"
rand = "0.8.5"
